steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/tftstocks:$COMMIT_SHA', '.']

  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/tftstocks:$COMMIT_SHA']

  # Deploy the image to Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'tftstocks'
    - '--image'
    - 'gcr.io/$PROJECT_ID/tftstocks:$COMMIT_SHA'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--update-secrets'
    - 'MONGO_URI=mongo_uri:latest,RIOT_API_KEY=riot_api_key:latest,SECRET_KEY=secret_key:latest'

images:
  - 'gcr.io/$PROJECT_ID/tftstocks:$COMMIT_SHA'
